# These are supported funding model platforms

github: [Vuppala Rohit Anajn]
patreon: Vuppala Rohit Anjan
open_collective: # Replace with a single Open Collective username
ko_fi: lekoarts
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
